//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopTC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.CTHoaDon = new HashSet<CTHoaDon>();
        }
    
        public string MaHD { get; set; }
        public string MaUser { get; set; }
        public System.DateTime NgayTao { get; set; }
        public int TongTien { get; set; }
        public string TenNguoiShip { get; set; }
        public string DiaChiShip { get; set; }
        public string SDTShip { get; set; }
        public string EmailShip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHoaDon> CTHoaDon { get; set; }
        public virtual Users Users { get; set; }
    }
}
