//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopTC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaGiamGia
    {
        public string MaCode { get; set; }
        public string GiaTriMa { get; set; }
        public int SoLuong { get; set; }
        public double GiamGia { get; set; }
    }
}
