//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopTC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLBHTCEntities : DbContext
    {
        public QLBHTCEntities()
            : base("name=QLBHTCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HoaDon> HoaDon { get; set; }
        public virtual DbSet<LoaiThuCung> LoaiThuCung { get; set; }
        public virtual DbSet<MaGiamGia> MaGiamGia { get; set; }
        public virtual DbSet<NHACC> NHACC { get; set; }
        public virtual DbSet<THAMSO> THAMSO { get; set; }
        public virtual DbSet<ThuCung> ThuCung { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<CTHoaDon> CTHoaDon { get; set; }
    }
}
