//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopTC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuCung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThuCung()
        {
            this.CTHoaDon = new HashSet<CTHoaDon>();
        }
    
        public string MaTC { get; set; }
        public string TenTC { get; set; }
        public int GiaTC { get; set; }
        public int SoLuong { get; set; }
        public Nullable<bool> GT { get; set; }
        public string MoTa { get; set; }
        public string HinhAnhMH { get; set; }
        public string MaLoai { get; set; }
        public string MaCC { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
    
        public virtual LoaiThuCung LoaiThuCung { get; set; }
        public virtual NHACC NHACC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHoaDon> CTHoaDon { get; set; }
    }
}
